### ISSUE TITLE
geom_text_repel interaction

### ISSUE THREAD

**Issue by archgen** [hughjonesd/ggmagnify#16] opened 2023-06-02 12:13 UTC
Hi, I am wondering if there is a way of restricting the geom_text_repel package to plot labels within the magnified region? 
Many thanks!

**Comment by hughjonesd** [comment] 2023-06-02 12:17
This looks like a help request, not a bug or enhancement request. Please don't use GitHub to ask for help: it wastes my time and clutters the issue tracker. If I'm wrong and there's a bug or enhancement here, please clarify.

**Comment by archgen** [comment] 2023-06-02 12:50
Fair enough.. An enhancement request (if possible) to have ggmagnify include labels either natively within the software functionality, or interacting with other packages such as geom_text_repel.

**Comment by hughjonesd** [comment] 2023-06-02 14:11
This is out of scope; you can do what you want already using the `plot` argument.

**Closed** 2023-06-02 14:11 UTC
